# Generated by Django 4.2.3 on 2023-07-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_subject_subjectmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectmarks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentmarks",
                to="home.student",
            ),
        ),
    ]
