# Generated by Django 4.2.3 on 2023-07-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_subjectmarks_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="studentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(unique=True)),
                ("date_of_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_rank",
                        to="home.student",
                    ),
                ),
            ],
        ),
    ]
